/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fixture.view.gruposview;

import fixture.model.Fase;
import fixture.model.Grupo;
import fixture.model.Partido;
import fixture.repository.GrupoRepository;
import fixture.repository.PartidoRepository;
import fixture.repository.migrations.GruposMigrations;
import fixture.repository.migrations.PartidosMigrations;
import fixture.view.VentanaFaseGrupos;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Nico
 */
public class GrupoConstructor extends javax.swing.JFrame {

    /**
     * Creates new form GrupoConstructor
     */
    char letraGrupo;
    PartidoRepository partidoRepository;
    GrupoRepository grupoRepository;
    //
    public GrupoConstructor(char letra) {
        this.letraGrupo = letra;
        initComponents();
        cargarEquipos();
        inicializarGrupo(letraGrupo);
    }

    private GrupoConstructor() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void close(){
    WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void cargarEquipos(){
        PartidosMigrations.up();
        GruposMigrations.up();
        partidoRepository = new PartidoRepository();
        grupoRepository = new GrupoRepository();
    };
    private void inicializarGrupo(char letraGrupo){
        Grupo grupo = grupoRepository.get(letraGrupo);
        ArrayList<Partido> partidos = partidoRepository.findBy(Fase.DE_GRUPOS, grupo);
        String titulo = "Grupo " + letraGrupo;
        jLabelTitulo.setText(titulo.toUpperCase());
        //
        List<JLabel> equiposVisit; 
        equiposVisit = new ArrayList();
        List<JLabel> equiposLocal;
        equiposLocal = new ArrayList();
        List<JLabel> estadios;
        estadios = new ArrayList();
        List<JLabel> fechas;
        fechas= new ArrayList();
        //
        equiposVisit.add(equipoVisit1);
        equiposVisit.add(equipoVisit2);
        equiposVisit.add(equipoVisit3);
        equiposVisit.add(equipoVisit4);
        equiposVisit.add(equipoVisit5);
        equiposVisit.add(equipoVisit6);
        //
        equiposLocal.add(equipoLocal1);
        equiposLocal.add(equipoLocal2);
        equiposLocal.add(equipoLocal3);
        equiposLocal.add(equipoLocal4);
        equiposLocal.add(equipoLocal5);
        equiposLocal.add(equipoLocal6);
        //
        estadios.add(estadioPartido1);
        estadios.add(estadioPartido2);
        estadios.add(estadioPartido3);
        estadios.add(estadioPartido4);
        estadios.add(estadioPartido5);
        estadios.add(estadioPartido6);
        //
        fechas.add(fechaPartido1);
        fechas.add(fechaPartido2);
        fechas.add(fechaPartido3);
        fechas.add(fechaPartido4);
        fechas.add(fechaPartido5);
        fechas.add(fechaPartido6);
        //
        Collections.sort(partidos,new Comparator<Partido>() {
            @Override
            public int compare(Partido o1, Partido o2) {
                return o1.getFechaYHora().isBefore(o2.getFechaYHora()) ? -1 :1 ; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        
        //
        int i = 0;
        JLabel txt = new JLabel();
        for (Partido partido : partidos) {
            equiposVisit.get(i).setText(partido.getEquipo2().getNombre());
            equiposLocal.get(i).setText(partido.getEquipo1().getNombre());
            estadios.get(i).setText(partido.getEstadio().getNombre());
            fechas.get(i++).setText(partido.getFechaYHora().toString());
            
        }
        
        
    
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        logoTop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        panelAFila1 = new javax.swing.JPanel();
        lblFechaPartidoA1 = new javax.swing.JLabel();
        lblEquipoLocalA1 = new javax.swing.JLabel();
        lblEquipoVisitanteA1 = new javax.swing.JLabel();
        lblNombreEstadioA1 = new javax.swing.JLabel();
        jSeparatorA1 = new javax.swing.JSeparator();
        golesField1_A1 = new javax.swing.JFormattedTextField();
        golesField2_A1 = new javax.swing.JFormattedTextField();
        guionA1 = new javax.swing.JLabel();
        panelAFila2 = new javax.swing.JPanel();
        lblFechaPartidoA2 = new javax.swing.JLabel();
        lblEquipoLocalA2 = new javax.swing.JLabel();
        lblEquipoVisitanteA2 = new javax.swing.JLabel();
        lblNombreEstadioA2 = new javax.swing.JLabel();
        jSeparatorA2 = new javax.swing.JSeparator();
        golesField1_A2 = new javax.swing.JFormattedTextField();
        golesField2_A2 = new javax.swing.JFormattedTextField();
        guionA2 = new javax.swing.JLabel();
        panelAFila3 = new javax.swing.JPanel();
        lblFechaPartidoA3 = new javax.swing.JLabel();
        lblEquipoLocalA3 = new javax.swing.JLabel();
        lblEquipoVisitanteA3 = new javax.swing.JLabel();
        lblNombreEstadioA3 = new javax.swing.JLabel();
        jSeparatorA3 = new javax.swing.JSeparator();
        golesField1_A3 = new javax.swing.JFormattedTextField();
        golesField2_A3 = new javax.swing.JFormattedTextField();
        guionA3 = new javax.swing.JLabel();
        panelAFila4 = new javax.swing.JPanel();
        lblFechaPartidoA4 = new javax.swing.JLabel();
        lblEquipoLocalA4 = new javax.swing.JLabel();
        lblEquipoVisitanteA4 = new javax.swing.JLabel();
        lblNombreEstadioA4 = new javax.swing.JLabel();
        jSeparatorA4 = new javax.swing.JSeparator();
        golesField1_A4 = new javax.swing.JFormattedTextField();
        golesField2_A4 = new javax.swing.JFormattedTextField();
        guionA4 = new javax.swing.JLabel();
        panelAFila5 = new javax.swing.JPanel();
        lblFechaPartidoA5 = new javax.swing.JLabel();
        lblEquipoLocalA5 = new javax.swing.JLabel();
        lblEquipoVisitanteA5 = new javax.swing.JLabel();
        lblNombreEstadioA5 = new javax.swing.JLabel();
        jSeparatorA5 = new javax.swing.JSeparator();
        golesField1_A5 = new javax.swing.JFormattedTextField();
        golesField2_A5 = new javax.swing.JFormattedTextField();
        guionA5 = new javax.swing.JLabel();
        panelAFila6 = new javax.swing.JPanel();
        lblFechaPartidoA6 = new javax.swing.JLabel();
        lblEquipoLocalA6 = new javax.swing.JLabel();
        lblEquipoVisitanteA6 = new javax.swing.JLabel();
        lblNombreEstadioA6 = new javax.swing.JLabel();
        jSeparatorA6 = new javax.swing.JSeparator();
        golesField1_A6 = new javax.swing.JFormattedTextField();
        golesField2_A6 = new javax.swing.JFormattedTextField();
        guionA6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTitulo.setText("Grupo A");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/qatar_2022_logo.png"))); // NOI18N
        logoTop.setText("jLabel1");
        getContentPane().add(logoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 151, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaPartidoA1.setText("FechaPartido");

        lblEquipoLocalA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA1.setText("Equipo Local");

        lblEquipoVisitanteA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA1.setText("Equipo Visitante");
        lblEquipoVisitanteA1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA1.setText("NombreEstadio");

        golesField1_A1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA1.setText("-");

        javax.swing.GroupLayout panelAFila1Layout = new javax.swing.GroupLayout(panelAFila1);
        panelAFila1.setLayout(panelAFila1Layout);
        panelAFila1Layout.setHorizontalGroup(
            panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA1)
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila1Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA1)))
                .addContainerGap())
        );
        panelAFila1Layout.setVerticalGroup(
            panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila1Layout.createSequentialGroup()
                .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA1))
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA1)
                            .addComponent(lblEquipoLocalA1)
                            .addComponent(golesField1_A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA1))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelAFila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 530, -1));

        lblFechaPartidoA2.setText("FechaPartido");

        lblEquipoLocalA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA2.setText("Equipo Local");

        lblEquipoVisitanteA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA2.setText("Equipo Visitante");
        lblEquipoVisitanteA2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA2.setText("NombreEstadio");

        golesField1_A2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA2.setText("-");

        javax.swing.GroupLayout panelAFila2Layout = new javax.swing.GroupLayout(panelAFila2);
        panelAFila2.setLayout(panelAFila2Layout);
        panelAFila2Layout.setHorizontalGroup(
            panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA2)
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila2Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA2)))
                .addContainerGap())
        );
        panelAFila2Layout.setVerticalGroup(
            panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila2Layout.createSequentialGroup()
                .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA2))
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA2)
                            .addComponent(lblEquipoLocalA2)
                            .addComponent(golesField1_A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA2))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelAFila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 530, -1));

        lblFechaPartidoA3.setText("FechaPartido");

        lblEquipoLocalA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA3.setText("Equipo Local");

        lblEquipoVisitanteA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA3.setText("Equipo Visitante");
        lblEquipoVisitanteA3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA3.setText("NombreEstadio");

        golesField1_A3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA3.setText("-");

        javax.swing.GroupLayout panelAFila3Layout = new javax.swing.GroupLayout(panelAFila3);
        panelAFila3.setLayout(panelAFila3Layout);
        panelAFila3Layout.setHorizontalGroup(
            panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA3)
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila3Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA3)))
                .addContainerGap())
        );
        panelAFila3Layout.setVerticalGroup(
            panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila3Layout.createSequentialGroup()
                .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA3))
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA3)
                            .addComponent(lblEquipoLocalA3)
                            .addComponent(golesField1_A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA3))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelAFila3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 178, 530, -1));

        lblFechaPartidoA4.setText("FechaPartido");

        lblEquipoLocalA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA4.setText("Equipo Local");

        lblEquipoVisitanteA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA4.setText("Equipo Visitante");
        lblEquipoVisitanteA4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA4.setText("NombreEstadio");

        golesField1_A4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA4.setText("-");

        javax.swing.GroupLayout panelAFila4Layout = new javax.swing.GroupLayout(panelAFila4);
        panelAFila4.setLayout(panelAFila4Layout);
        panelAFila4Layout.setHorizontalGroup(
            panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA4)
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila4Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA4)))
                .addContainerGap())
        );
        panelAFila4Layout.setVerticalGroup(
            panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila4Layout.createSequentialGroup()
                .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA4))
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA4)
                            .addComponent(lblEquipoLocalA4)
                            .addComponent(golesField1_A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA4))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelAFila4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 267, 530, -1));

        lblFechaPartidoA5.setText("FechaPartido");

        lblEquipoLocalA5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA5.setText("Equipo Local");

        lblEquipoVisitanteA5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA5.setText("Equipo Visitante");
        lblEquipoVisitanteA5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA5.setText("NombreEstadio");

        golesField1_A5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA5.setText("-");

        javax.swing.GroupLayout panelAFila5Layout = new javax.swing.GroupLayout(panelAFila5);
        panelAFila5.setLayout(panelAFila5Layout);
        panelAFila5Layout.setHorizontalGroup(
            panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA5)
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila5Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA5)))
                .addContainerGap())
        );
        panelAFila5Layout.setVerticalGroup(
            panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila5Layout.createSequentialGroup()
                .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA5))
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA5)
                            .addComponent(lblEquipoLocalA5)
                            .addComponent(golesField1_A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA5))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelAFila5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 356, 530, -1));

        lblFechaPartidoA6.setText("FechaPartido");

        lblEquipoLocalA6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA6.setText("Equipo Local");

        lblEquipoVisitanteA6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA6.setText("Equipo Visitante");
        lblEquipoVisitanteA6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA6.setText("NombreEstadio");

        golesField1_A6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        golesField2_A6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        guionA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA6.setText("-");

        javax.swing.GroupLayout panelAFila6Layout = new javax.swing.GroupLayout(panelAFila6);
        panelAFila6.setLayout(panelAFila6Layout);
        panelAFila6Layout.setHorizontalGroup(
            panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA6)
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila6Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA6, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA6)))
                .addContainerGap())
        );
        panelAFila6Layout.setVerticalGroup(
            panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila6Layout.createSequentialGroup()
                .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA6))
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA6)
                            .addComponent(lblEquipoLocalA6)
                            .addComponent(golesField1_A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA6))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelAFila6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 445, 530, -1));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        VentanaFaseGrupos ventanaFaseGrupos = new VentanaFaseGrupos();
        ventanaFaseGrupos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupoConstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupoConstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupoConstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoConstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupoConstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField golesField1_A1;
    private javax.swing.JFormattedTextField golesField1_A2;
    private javax.swing.JFormattedTextField golesField1_A3;
    private javax.swing.JFormattedTextField golesField1_A4;
    private javax.swing.JFormattedTextField golesField1_A5;
    private javax.swing.JFormattedTextField golesField1_A6;
    private javax.swing.JFormattedTextField golesField2_A1;
    private javax.swing.JFormattedTextField golesField2_A2;
    private javax.swing.JFormattedTextField golesField2_A3;
    private javax.swing.JFormattedTextField golesField2_A4;
    private javax.swing.JFormattedTextField golesField2_A5;
    private javax.swing.JFormattedTextField golesField2_A6;
    private javax.swing.JLabel guionA1;
    private javax.swing.JLabel guionA2;
    private javax.swing.JLabel guionA3;
    private javax.swing.JLabel guionA4;
    private javax.swing.JLabel guionA5;
    private javax.swing.JLabel guionA6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorA1;
    private javax.swing.JSeparator jSeparatorA2;
    private javax.swing.JSeparator jSeparatorA3;
    private javax.swing.JSeparator jSeparatorA4;
    private javax.swing.JSeparator jSeparatorA5;
    private javax.swing.JSeparator jSeparatorA6;
    private javax.swing.JLabel lblEquipoLocalA1;
    private javax.swing.JLabel lblEquipoLocalA2;
    private javax.swing.JLabel lblEquipoLocalA3;
    private javax.swing.JLabel lblEquipoLocalA4;
    private javax.swing.JLabel lblEquipoLocalA5;
    private javax.swing.JLabel lblEquipoLocalA6;
    private javax.swing.JLabel lblEquipoVisitanteA1;
    private javax.swing.JLabel lblEquipoVisitanteA2;
    private javax.swing.JLabel lblEquipoVisitanteA3;
    private javax.swing.JLabel lblEquipoVisitanteA4;
    private javax.swing.JLabel lblEquipoVisitanteA5;
    private javax.swing.JLabel lblEquipoVisitanteA6;
    private javax.swing.JLabel lblFechaPartidoA1;
    private javax.swing.JLabel lblFechaPartidoA2;
    private javax.swing.JLabel lblFechaPartidoA3;
    private javax.swing.JLabel lblFechaPartidoA4;
    private javax.swing.JLabel lblFechaPartidoA5;
    private javax.swing.JLabel lblFechaPartidoA6;
    private javax.swing.JLabel lblNombreEstadioA1;
    private javax.swing.JLabel lblNombreEstadioA2;
    private javax.swing.JLabel lblNombreEstadioA3;
    private javax.swing.JLabel lblNombreEstadioA4;
    private javax.swing.JLabel lblNombreEstadioA5;
    private javax.swing.JLabel lblNombreEstadioA6;
    private javax.swing.JLabel logoTop;
    private javax.swing.JPanel panelAFila1;
    private javax.swing.JPanel panelAFila2;
    private javax.swing.JPanel panelAFila3;
    private javax.swing.JPanel panelAFila4;
    private javax.swing.JPanel panelAFila5;
    private javax.swing.JPanel panelAFila6;
    // End of variables declaration//GEN-END:variables
}
