/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fixture.view;

/**
 *
 * @author abreg
 */
public class GrupoTab extends javax.swing.JPanel {

    private char letraGrupo;
    
    public GrupoTab(char letra) {
        this.letraGrupo = letra;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedorGrupoA = new javax.swing.JPanel();
        tituloGrupoA = new javax.swing.JLabel();
        contenedorPartidosGrupoA = new javax.swing.JPanel();
        panelFilaPartido = new javax.swing.JPanel();
        horarioLabel = new javax.swing.JLabel();
        estadioLabel = new javax.swing.JLabel();
        equipo1Label = new javax.swing.JLabel();
        equipo2Label = new javax.swing.JLabel();
        equipo1TextField = new javax.swing.JFormattedTextField();
        equipo2TextField = new javax.swing.JFormattedTextField();

        panelContenedorGrupoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        panelContenedorGrupoA.setLayout(new java.awt.BorderLayout());

        tituloGrupoA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloGrupoA.setForeground(new java.awt.Color(154, 16, 50));
        tituloGrupoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloGrupoA.setText("GRUPO " + Character.toUpperCase(letraGrupo));
        panelContenedorGrupoA.add(tituloGrupoA, java.awt.BorderLayout.NORTH);

        contenedorPartidosGrupoA.setLayout(new java.awt.GridLayout(6, 1, 0, 2));

        horarioLabel.setText("jLabel1");

        estadioLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        estadioLabel.setText("jLabel1");

        equipo1Label.setText("jLabel1");

        equipo2Label.setText("jLabel1");

        equipo1TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        equipo2TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout panelFilaPartidoLayout = new javax.swing.GroupLayout(panelFilaPartido);
        panelFilaPartido.setLayout(panelFilaPartidoLayout);
        panelFilaPartidoLayout.setHorizontalGroup(
            panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilaPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadioLabel)
                .addContainerGap())
            .addGroup(panelFilaPartidoLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(equipo1Label)
                .addGap(57, 57, 57)
                .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(equipo2Label)
                .addGap(164, 164, 164))
        );
        panelFilaPartidoLayout.setVerticalGroup(
            panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilaPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioLabel)
                    .addComponent(estadioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipo1Label)
                    .addComponent(equipo2Label)
                    .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedorPartidosGrupoA.add(panelFilaPartido);

        panelContenedorGrupoA.add(contenedorPartidosGrupoA, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedorGrupoA, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedorGrupoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPartidosGrupoA;
    private javax.swing.JLabel equipo1Label;
    private javax.swing.JFormattedTextField equipo1TextField;
    private javax.swing.JLabel equipo2Label;
    private javax.swing.JFormattedTextField equipo2TextField;
    private javax.swing.JLabel estadioLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JPanel panelContenedorGrupoA;
    private javax.swing.JPanel panelFilaPartido;
    private javax.swing.JLabel tituloGrupoA;
    // End of variables declaration//GEN-END:variables
}
