/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fixture.view;

import fixture.model.Partido;
import java.util.ArrayList;
import static java.util.Objects.nonNull;

/**
 *
 * @author abreg
 */
public class GrupoTab extends javax.swing.JPanel {

    private char letraGrupo;
    private ArrayList<Partido> partidos;

    public GrupoTab(char letra, ArrayList<Partido> partidos) {
        this.letraGrupo = letra;
        this.partidos = partidos;
        initComponents();
        updateRows();
    }

    private void updateRows() {
        for (Partido partido : partidos) {
            if (nonNull(partido)) {
                panelContenedorGrupo.add(new PartidoRow(partido));
            }
        }
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloGrupoA = new javax.swing.JLabel();
        panelContenedorGrupo = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        tituloGrupoA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloGrupoA.setForeground(new java.awt.Color(154, 16, 50));
        tituloGrupoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloGrupoA.setText("GRUPO " + Character.toUpperCase(letraGrupo));
        tituloGrupoA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(tituloGrupoA);

        panelContenedorGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        panelContenedorGrupo.setLayout(new javax.swing.BoxLayout(panelContenedorGrupo, javax.swing.BoxLayout.Y_AXIS));
        add(panelContenedorGrupo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedorGrupo;
    private javax.swing.JLabel tituloGrupoA;
    // End of variables declaration//GEN-END:variables
}
