/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fixture.view;

import fixture.model.Partido;

/**
 *
 * @author abreg
 */
public class PartidoRow extends javax.swing.JPanel {

    private Partido partido;
    /**
     * Creates new form PartidoRow
     * @param partido
     */
    public PartidoRow(Partido partido) {
        this.partido = partido;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFilaPartido = new javax.swing.JPanel();
        horarioLabel = new javax.swing.JLabel();
        estadioLabel = new javax.swing.JLabel();
        equipo1Label = new javax.swing.JLabel();
        equipo2Label = new javax.swing.JLabel();
        equipo1TextField = new javax.swing.JFormattedTextField();
        equipo2TextField = new javax.swing.JFormattedTextField();

        horarioLabel.setText("jLabel1");

        estadioLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        estadioLabel.setText("jLabel1");

        equipo1Label.setText("jLabel1");

        equipo2Label.setText("jLabel1");

        equipo1TextField.setBackground(new java.awt.Color(255, 255, 255));
        equipo1TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        equipo2TextField.setBackground(new java.awt.Color(255, 255, 255));
        equipo2TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout panelFilaPartidoLayout = new javax.swing.GroupLayout(panelFilaPartido);
        panelFilaPartido.setLayout(panelFilaPartidoLayout);
        panelFilaPartidoLayout.setHorizontalGroup(
            panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilaPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(horarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estadioLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilaPartidoLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(equipo1Label)
                .addGap(18, 18, 18)
                .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(equipo2Label)
                .addGap(226, 226, 226))
        );
        panelFilaPartidoLayout.setVerticalGroup(
            panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilaPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horarioLabel)
                    .addComponent(estadioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFilaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipo1Label)
                    .addComponent(equipo2Label)
                    .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(panelFilaPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFilaPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equipo1Label;
    private javax.swing.JFormattedTextField equipo1TextField;
    private javax.swing.JLabel equipo2Label;
    private javax.swing.JFormattedTextField equipo2TextField;
    private javax.swing.JLabel estadioLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JPanel panelFilaPartido;
    // End of variables declaration//GEN-END:variables
}
