/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fixture.view;

import fixture.model.Partido;
import java.awt.Image;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/**
 *
 * @author abreg
 */
public class PartidoRow extends javax.swing.JPanel {

    private Partido partido;
    /**
     * Creates new form PartidoRow
     * @param partido
     */
    public PartidoRow(Partido partido) {
        this.partido = partido;
        initComponents();
        
        horarioLabel.setText(partido.getFechaYHora().format(DateTimeFormatter.ofPattern("d MMM uuuu")));
        estadioLabel.setText(partido.getEstadio().getNombre());
        
        
        ImageIcon imageIconEquipo1 = new ImageIcon(new ImageIcon(getClass().getResource("/static/img/banderas/" + partido.getEquipo1().getId() + ".png")).getImage().getScaledInstance(50, 33, Image.SCALE_SMOOTH)); 
        equipo1Label.setIcon(imageIconEquipo1);
        equipo1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        equipo1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        equipo1Label.setText(partido.getEquipo1().getNombre());
        
        ImageIcon imageIconEquipo2 = new ImageIcon(new ImageIcon(getClass().getResource("/static/img/banderas/" + partido.getEquipo2().getId() + ".png")).getImage().getScaledInstance(50, 33, Image.SCALE_SMOOTH)); 
        equipo2Label.setIcon(imageIconEquipo2);
        equipo2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        equipo2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        equipo2Label.setText(partido.getEquipo2().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        estadioLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        panelFilaPartido = new javax.swing.JPanel();
        equipo1Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        equipo1TextField = new javax.swing.JFormattedTextField();
        guionLabel = new javax.swing.JLabel();
        equipo2TextField = new javax.swing.JFormattedTextField();
        equipo2Label = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(734, 100));
        setPreferredSize(new java.awt.Dimension(734, 100));
        setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setPreferredSize(new java.awt.Dimension(734, 40));

        estadioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estadioLabel.setText("jLabel1");
        estadioLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        horarioLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(horarioLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadioLabel)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(horarioLabel)
                        .addComponent(estadioLabel))
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        add(jPanel2);

        panelFilaPartido.setMinimumSize(new java.awt.Dimension(734, 100));
        panelFilaPartido.setPreferredSize(new java.awt.Dimension(734, 100));

        equipo1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        equipo1Label.setText("jLabel1");
        equipo1Label.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        equipo1Label.setMaximumSize(null);
        equipo1Label.setMinimumSize(null);
        equipo1Label.setPreferredSize(null);
        panelFilaPartido.add(equipo1Label);

        equipo1TextField.setBackground(new java.awt.Color(255, 255, 255));
        equipo1TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        guionLabel.setText("-");

        equipo2TextField.setBackground(new java.awt.Color(255, 255, 255));
        equipo2TextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(guionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(equipo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guionLabel)
                    .addComponent(equipo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelFilaPartido.add(jPanel3);

        equipo2Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        equipo2Label.setText("jLabel1");
        equipo2Label.setToolTipText("");
        equipo2Label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        equipo2Label.setMaximumSize(null);
        equipo2Label.setMinimumSize(null);
        equipo2Label.setPreferredSize(null);
        panelFilaPartido.add(equipo2Label);

        add(panelFilaPartido);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equipo1Label;
    private javax.swing.JFormattedTextField equipo1TextField;
    private javax.swing.JLabel equipo2Label;
    private javax.swing.JFormattedTextField equipo2TextField;
    private javax.swing.JLabel estadioLabel;
    private javax.swing.JLabel guionLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelFilaPartido;
    // End of variables declaration//GEN-END:variables
}
