/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fixture.view;

import fixture.model.Partido;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author abreg
 */
public class Ventana extends javax.swing.JFrame {

    private HashMap<Character, ArrayList<Partido>> grupoPartidos;

    public void setGrupoPartido(char letraGrupo, ArrayList<Partido> partidos) {
        this.grupoPartidos.put(letraGrupo, partidos);

        switch (letraGrupo) {
            case 'a':
                this.panelGrupoA.add(new GrupoTab('a', this.grupoPartidos.get('a')));
                break;
            case 'b':
                this.panelGrupoB.add(new GrupoTab('b', this.grupoPartidos.get('b')));
                break;
            case 'c':
                this.panelGrupoC.add(new GrupoTab('c', this.grupoPartidos.get('c')));
                break;
            case 'd':
                this.panelGrupoD.add(new GrupoTab('d', this.grupoPartidos.get('d')));
                break;
            case 'e':
                this.panelGrupoE.add(new GrupoTab('e', this.grupoPartidos.get('e')));
                break;
            case 'f':
                this.panelGrupoF.add(new GrupoTab('f', this.grupoPartidos.get('f')));
                break;
            case 'g':
                this.panelGrupoG.add(new GrupoTab('g', this.grupoPartidos.get('g')));
                break;
            case 'h':
                this.panelGrupoH.add(new GrupoTab('h', this.grupoPartidos.get('h')));
                break;
        }
        this.pack();
    }

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        this.grupoPartidos = new HashMap();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelGrupoA = new javax.swing.JPanel();
        panelGrupoB = new javax.swing.JPanel();
        panelGrupoC = new javax.swing.JPanel();
        panelGrupoD = new javax.swing.JPanel();
        panelGrupoE = new javax.swing.JPanel();
        panelGrupoF = new javax.swing.JPanel();
        panelGrupoG = new javax.swing.JPanel();
        panelGrupoH = new javax.swing.JPanel();
        panelOctavos = new javax.swing.JPanel();
        panelCuartos = new javax.swing.JPanel();
        panelSemifinales = new javax.swing.JPanel();
        panelTercerPuesto = new javax.swing.JPanel();
        panelFinal = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixture interactivo - Qatar 2022");
        setBounds(new java.awt.Rectangle(0, 0, 800, 800));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setName("frameBase"); // NOI18N
        setSize(new java.awt.Dimension(1280, 720));

        panelMain.setAlignmentX(0.0F);
        panelMain.setAlignmentY(0.0F);
        panelMain.setMaximumSize(null);
        panelMain.setName(""); // NOI18N

        panelBody.setMaximumSize(null);
        panelBody.setPreferredSize(new java.awt.Dimension(720, 405));

        tabbedPane.setMaximumSize(null);
        tabbedPane.addTab("A", panelGrupoA);

        panelGrupoB.setMaximumSize(null);
        tabbedPane.addTab("B", panelGrupoB);

        panelGrupoC.setMaximumSize(null);
        tabbedPane.addTab("C", panelGrupoC);

        panelGrupoD.setMaximumSize(null);
        tabbedPane.addTab("D", panelGrupoD);

        panelGrupoE.setMaximumSize(null);
        tabbedPane.addTab("E", panelGrupoE);

        panelGrupoF.setMaximumSize(null);
        tabbedPane.addTab("F", panelGrupoF);

        panelGrupoG.setMaximumSize(null);
        tabbedPane.addTab("G", panelGrupoG);

        panelGrupoH.setMaximumSize(null);
        tabbedPane.addTab("H", panelGrupoH);

        panelOctavos.setMaximumSize(null);
        tabbedPane.addTab("OCTAVOS", panelOctavos);

        panelCuartos.setMaximumSize(null);
        tabbedPane.addTab("CUARTOS", panelCuartos);

        panelSemifinales.setMaximumSize(null);
        tabbedPane.addTab("SEMIFINALES", panelSemifinales);

        panelTercerPuesto.setMaximumSize(null);
        tabbedPane.addTab("3er PUESTO", panelTercerPuesto);

        panelFinal.setMaximumSize(null);
        tabbedPane.addTab("FINAL", panelFinal);

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.getAccessibleContext().setAccessibleName("tabB");

        panelHeader.setMaximumSize(null);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/qatar_2022_logo.png"))); // NOI18N
        labelLogo.setText("LOGO");

        labelTitulo.setBackground(new java.awt.Color(46, 30, 34));
        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(154, 16, 50));
        labelTitulo.setText("QATAR 2022 - FIXTURE");

        labelSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubtitulo.setForeground(new java.awt.Color(154, 16, 50));
        labelSubtitulo.setText("del 21 de noviembre al 18 de diciembre de 2022");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelCuartos;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelGrupoA;
    private javax.swing.JPanel panelGrupoB;
    private javax.swing.JPanel panelGrupoC;
    private javax.swing.JPanel panelGrupoD;
    private javax.swing.JPanel panelGrupoE;
    private javax.swing.JPanel panelGrupoF;
    private javax.swing.JPanel panelGrupoG;
    private javax.swing.JPanel panelGrupoH;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelOctavos;
    private javax.swing.JPanel panelSemifinales;
    private javax.swing.JPanel panelTercerPuesto;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
