/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fixture.view;

import fixture.model.Fase;
import fixture.model.Grupo;
import fixture.model.Partido;
import fixture.repository.GrupoRepository;
import fixture.repository.PartidoRepository;
import fixture.repository.migrations.GruposMigrations;
import fixture.repository.migrations.PartidosMigrations;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author abreg
 */
public class Ventana extends javax.swing.JFrame {

    private ImageIcon logoImage;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        cargarRepositorios();
        
        loadPartidosGrupoA();
        
        loadPartidosGrupoB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelBody = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelGrupoA = new javax.swing.JPanel();
        jScrollPaneA = new javax.swing.JScrollPane();
        panelInteriorA = new javax.swing.JPanel();
        panelAFila1 = new javax.swing.JPanel();
        lblFechaPartidoA1 = new javax.swing.JLabel();
        lblEquipoLocalA1 = new javax.swing.JLabel();
        lblEquipoVisitanteA1 = new javax.swing.JLabel();
        lblNombreEstadioA1 = new javax.swing.JLabel();
        jSeparatorA1 = new javax.swing.JSeparator();
        golesField1_A1 = new javax.swing.JFormattedTextField();
        golesField2_A1 = new javax.swing.JFormattedTextField();
        guionA1 = new javax.swing.JLabel();
        panelAFila2 = new javax.swing.JPanel();
        lblFechaPartidoA2 = new javax.swing.JLabel();
        lblEquipoLocalA2 = new javax.swing.JLabel();
        lblEquipoVisitanteA2 = new javax.swing.JLabel();
        lblNombreEstadioA2 = new javax.swing.JLabel();
        jSeparatorA2 = new javax.swing.JSeparator();
        golesField1_A2 = new javax.swing.JFormattedTextField();
        golesField2_A2 = new javax.swing.JFormattedTextField();
        guionA2 = new javax.swing.JLabel();
        panelAFila3 = new javax.swing.JPanel();
        lblFechaPartidoA3 = new javax.swing.JLabel();
        lblEquipoLocalA3 = new javax.swing.JLabel();
        lblEquipoVisitanteA3 = new javax.swing.JLabel();
        lblNombreEstadioA3 = new javax.swing.JLabel();
        jSeparatorA3 = new javax.swing.JSeparator();
        golesField1_A3 = new javax.swing.JFormattedTextField();
        golesField2_A3 = new javax.swing.JFormattedTextField();
        guionA3 = new javax.swing.JLabel();
        panelAFila4 = new javax.swing.JPanel();
        lblFechaPartidoA4 = new javax.swing.JLabel();
        lblEquipoLocalA4 = new javax.swing.JLabel();
        lblEquipoVisitanteA4 = new javax.swing.JLabel();
        lblNombreEstadioA4 = new javax.swing.JLabel();
        jSeparatorA4 = new javax.swing.JSeparator();
        golesField1_A4 = new javax.swing.JFormattedTextField();
        golesField2_A4 = new javax.swing.JFormattedTextField();
        guionA4 = new javax.swing.JLabel();
        panelAFila5 = new javax.swing.JPanel();
        lblFechaPartidoA5 = new javax.swing.JLabel();
        lblEquipoLocalA5 = new javax.swing.JLabel();
        lblEquipoVisitanteA5 = new javax.swing.JLabel();
        lblNombreEstadioA5 = new javax.swing.JLabel();
        jSeparatorA5 = new javax.swing.JSeparator();
        golesField1_A5 = new javax.swing.JFormattedTextField();
        golesField2_A5 = new javax.swing.JFormattedTextField();
        guionA5 = new javax.swing.JLabel();
        panelAFila6 = new javax.swing.JPanel();
        lblFechaPartidoA6 = new javax.swing.JLabel();
        lblEquipoLocalA6 = new javax.swing.JLabel();
        lblEquipoVisitanteA6 = new javax.swing.JLabel();
        lblNombreEstadioA6 = new javax.swing.JLabel();
        jSeparatorA6 = new javax.swing.JSeparator();
        golesField1_A6 = new javax.swing.JFormattedTextField();
        golesField2_A6 = new javax.swing.JFormattedTextField();
        guionA6 = new javax.swing.JLabel();
        panelGrupoB = new javax.swing.JPanel();
        jScrollPaneB = new javax.swing.JScrollPane();
        panelInteriorB = new javax.swing.JPanel();
        panelBFila1 = new javax.swing.JPanel();
        lblFechaPartidoB1 = new javax.swing.JLabel();
        lblEquipoLocalB1 = new javax.swing.JLabel();
        lblEquipoVisitanteB1 = new javax.swing.JLabel();
        lblNombreEstadioB1 = new javax.swing.JLabel();
        jSeparatorB1 = new javax.swing.JSeparator();
        golesField1_B1 = new javax.swing.JFormattedTextField();
        golesField2_B1 = new javax.swing.JFormattedTextField();
        guionA7 = new javax.swing.JLabel();
        panelBFila2 = new javax.swing.JPanel();
        lblFechaPartidoB2 = new javax.swing.JLabel();
        lblEquipoLocalB2 = new javax.swing.JLabel();
        lblEquipoVisitanteB2 = new javax.swing.JLabel();
        lblNombreEstadioB2 = new javax.swing.JLabel();
        jSeparatorB2 = new javax.swing.JSeparator();
        golesField1_B2 = new javax.swing.JFormattedTextField();
        golesField2_B2 = new javax.swing.JFormattedTextField();
        guionB2 = new javax.swing.JLabel();
        panelBFila3 = new javax.swing.JPanel();
        lblFechaPartidoB3 = new javax.swing.JLabel();
        lblEquipoLocalB3 = new javax.swing.JLabel();
        lblEquipoVisitanteB3 = new javax.swing.JLabel();
        lblNombreEstadioB3 = new javax.swing.JLabel();
        jSeparatorB3 = new javax.swing.JSeparator();
        golesField1_B3 = new javax.swing.JFormattedTextField();
        golesField2_B3 = new javax.swing.JFormattedTextField();
        B3 = new javax.swing.JLabel();
        panelBFila4 = new javax.swing.JPanel();
        lblFechaPartidoB4 = new javax.swing.JLabel();
        lblEquipoLocalB4 = new javax.swing.JLabel();
        lblEquipoVisitanteB4 = new javax.swing.JLabel();
        lblNombreEstadioB4 = new javax.swing.JLabel();
        jSeparatorB4 = new javax.swing.JSeparator();
        golesField1_B4 = new javax.swing.JFormattedTextField();
        golesField2_B4 = new javax.swing.JFormattedTextField();
        guionB4 = new javax.swing.JLabel();
        panelBFila5 = new javax.swing.JPanel();
        lblFechaPartidoB5 = new javax.swing.JLabel();
        lblEquipoLocalB5 = new javax.swing.JLabel();
        lblEquipoVisitanteB5 = new javax.swing.JLabel();
        lblNombreEstadioB5 = new javax.swing.JLabel();
        jSeparatorB5 = new javax.swing.JSeparator();
        golesField1_B5 = new javax.swing.JFormattedTextField();
        golesField2_B5 = new javax.swing.JFormattedTextField();
        guionB5 = new javax.swing.JLabel();
        panelBFila6 = new javax.swing.JPanel();
        lblFechaPartidoB6 = new javax.swing.JLabel();
        lblEquipoLocalB6 = new javax.swing.JLabel();
        lblEquipoVisitanteB6 = new javax.swing.JLabel();
        lblNombreEstadioB6 = new javax.swing.JLabel();
        jSeparatorB6 = new javax.swing.JSeparator();
        golesField1_B6 = new javax.swing.JFormattedTextField();
        golesField2_B6 = new javax.swing.JFormattedTextField();
        guionB6 = new javax.swing.JLabel();
        panelGrupoC = new javax.swing.JPanel();
        panelGrupoD = new javax.swing.JPanel();
        panelGrupoE = new javax.swing.JPanel();
        panelGrupoF = new javax.swing.JPanel();
        panelGrupoG = new javax.swing.JPanel();
        panelGrupoH = new javax.swing.JPanel();
        panelOctavos = new javax.swing.JPanel();
        panelCuartos = new javax.swing.JPanel();
        panelSemifinales = new javax.swing.JPanel();
        panelTercerPuesto = new javax.swing.JPanel();
        panelFinal = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelSubtitulo = new javax.swing.JLabel();
        labelLogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixture interactivo - Qatar 2022");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 800));
        setMinimumSize(null);
        setSize(new java.awt.Dimension(800, 800));

        panelMain.setMaximumSize(new java.awt.Dimension(1920, 1080));
        panelMain.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelBody.setPreferredSize(new java.awt.Dimension(1280, 263));

        tabbedPane.setMaximumSize(panelBody.getMinimumSize());

        panelGrupoA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInteriorA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaPartidoA1.setText("FechaPartido");

        lblEquipoLocalA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA1.setText("Equipo Local");

        lblEquipoVisitanteA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA1.setText("Equipo Visitante");
        lblEquipoVisitanteA1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA1.setText("NombreEstadio");

        guionA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA1.setText("-");

        javax.swing.GroupLayout panelAFila1Layout = new javax.swing.GroupLayout(panelAFila1);
        panelAFila1.setLayout(panelAFila1Layout);
        panelAFila1Layout.setHorizontalGroup(
            panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA1)
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila1Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA1)))
                .addContainerGap())
        );
        panelAFila1Layout.setVerticalGroup(
            panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila1Layout.createSequentialGroup()
                .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA1))
                    .addGroup(panelAFila1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA1)
                            .addComponent(lblEquipoLocalA1)
                            .addComponent(golesField1_A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA1))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 720, 90));

        lblFechaPartidoA2.setText("FechaPartido");

        lblEquipoLocalA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA2.setText("Equipo Local");

        lblEquipoVisitanteA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA2.setText("Equipo Visitante");
        lblEquipoVisitanteA2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA2.setText("NombreEstadio");

        guionA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA2.setText("-");

        javax.swing.GroupLayout panelAFila2Layout = new javax.swing.GroupLayout(panelAFila2);
        panelAFila2.setLayout(panelAFila2Layout);
        panelAFila2Layout.setHorizontalGroup(
            panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA2)
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila2Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA2)))
                .addContainerGap())
        );
        panelAFila2Layout.setVerticalGroup(
            panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila2Layout.createSequentialGroup()
                .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA2))
                    .addGroup(panelAFila2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA2)
                            .addComponent(lblEquipoLocalA2)
                            .addComponent(golesField1_A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA2))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 720, 90));

        lblFechaPartidoA3.setText("FechaPartido");

        lblEquipoLocalA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA3.setText("Equipo Local");

        lblEquipoVisitanteA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA3.setText("Equipo Visitante");
        lblEquipoVisitanteA3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA3.setText("NombreEstadio");

        guionA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA3.setText("-");

        javax.swing.GroupLayout panelAFila3Layout = new javax.swing.GroupLayout(panelAFila3);
        panelAFila3.setLayout(panelAFila3Layout);
        panelAFila3Layout.setHorizontalGroup(
            panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA3)
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila3Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA3)))
                .addContainerGap())
        );
        panelAFila3Layout.setVerticalGroup(
            panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila3Layout.createSequentialGroup()
                .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA3))
                    .addGroup(panelAFila3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA3)
                            .addComponent(lblEquipoLocalA3)
                            .addComponent(golesField1_A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA3))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 720, 90));

        lblFechaPartidoA4.setText("FechaPartido");

        lblEquipoLocalA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA4.setText("Equipo Local");

        lblEquipoVisitanteA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA4.setText("Equipo Visitante");
        lblEquipoVisitanteA4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA4.setText("NombreEstadio");

        guionA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA4.setText("-");

        javax.swing.GroupLayout panelAFila4Layout = new javax.swing.GroupLayout(panelAFila4);
        panelAFila4.setLayout(panelAFila4Layout);
        panelAFila4Layout.setHorizontalGroup(
            panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA4)
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila4Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA4)))
                .addContainerGap())
        );
        panelAFila4Layout.setVerticalGroup(
            panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila4Layout.createSequentialGroup()
                .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA4))
                    .addGroup(panelAFila4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA4)
                            .addComponent(lblEquipoLocalA4)
                            .addComponent(golesField1_A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA4))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 720, 90));

        lblFechaPartidoA5.setText("FechaPartido");

        lblEquipoLocalA5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA5.setText("Equipo Local");

        lblEquipoVisitanteA5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA5.setText("Equipo Visitante");
        lblEquipoVisitanteA5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA5.setText("NombreEstadio");

        guionA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA5.setText("-");

        javax.swing.GroupLayout panelAFila5Layout = new javax.swing.GroupLayout(panelAFila5);
        panelAFila5.setLayout(panelAFila5Layout);
        panelAFila5Layout.setHorizontalGroup(
            panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA5)
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila5Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA5)))
                .addContainerGap())
        );
        panelAFila5Layout.setVerticalGroup(
            panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila5Layout.createSequentialGroup()
                .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA5))
                    .addGroup(panelAFila5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA5)
                            .addComponent(lblEquipoLocalA5)
                            .addComponent(golesField1_A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA5))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 720, 90));

        lblFechaPartidoA6.setText("FechaPartido");

        lblEquipoLocalA6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalA6.setText("Equipo Local");

        lblEquipoVisitanteA6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteA6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteA6.setText("Equipo Visitante");
        lblEquipoVisitanteA6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioA6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioA6.setText("NombreEstadio");

        guionA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA6.setText("-");

        javax.swing.GroupLayout panelAFila6Layout = new javax.swing.GroupLayout(panelAFila6);
        panelAFila6.setLayout(panelAFila6Layout);
        panelAFila6Layout.setHorizontalGroup(
            panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorA6)
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioA6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAFila6Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteA6)))
                .addContainerGap())
        );
        panelAFila6Layout.setVerticalGroup(
            panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAFila6Layout.createSequentialGroup()
                .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoA6))
                    .addGroup(panelAFila6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioA6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteA6)
                            .addComponent(lblEquipoLocalA6)
                            .addComponent(golesField1_A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA6))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorA.add(panelAFila6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 720, 90));

        jScrollPaneA.setViewportView(panelInteriorA);

        panelGrupoA.add(jScrollPaneA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, 420));

        tabbedPane.addTab("A", panelGrupoA);

        panelGrupoB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInteriorB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaPartidoB1.setText("FechaPartido");

        lblEquipoLocalB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB1.setText("Equipo Local");

        lblEquipoVisitanteB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB1.setText("Equipo Visitante");
        lblEquipoVisitanteB1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB1.setText("NombreEstadio");

        guionA7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionA7.setText("-");

        javax.swing.GroupLayout panelBFila1Layout = new javax.swing.GroupLayout(panelBFila1);
        panelBFila1.setLayout(panelBFila1Layout);
        panelBFila1Layout.setHorizontalGroup(
            panelBFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB1)
                    .addGroup(panelBFila1Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila1Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionA7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB1)))
                .addContainerGap())
        );
        panelBFila1Layout.setVerticalGroup(
            panelBFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila1Layout.createSequentialGroup()
                .addGroup(panelBFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB1))
                    .addGroup(panelBFila1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB1)
                            .addComponent(lblEquipoLocalB1)
                            .addComponent(golesField1_B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionA7))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 730, 90));

        lblFechaPartidoB2.setText("FechaPartido");

        lblEquipoLocalB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB2.setText("Equipo Local");

        lblEquipoVisitanteB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB2.setText("Equipo Visitante");
        lblEquipoVisitanteB2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB2.setText("NombreEstadio");

        guionB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionB2.setText("-");

        javax.swing.GroupLayout panelBFila2Layout = new javax.swing.GroupLayout(panelBFila2);
        panelBFila2.setLayout(panelBFila2Layout);
        panelBFila2Layout.setHorizontalGroup(
            panelBFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB2)
                    .addGroup(panelBFila2Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila2Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB2)))
                .addContainerGap())
        );
        panelBFila2Layout.setVerticalGroup(
            panelBFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila2Layout.createSequentialGroup()
                .addGroup(panelBFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB2))
                    .addGroup(panelBFila2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB2)
                            .addComponent(lblEquipoLocalB2)
                            .addComponent(golesField1_B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionB2))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 90));

        lblFechaPartidoB3.setText("FechaPartido");

        lblEquipoLocalB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB3.setText("Equipo Local");

        lblEquipoVisitanteB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB3.setText("Equipo Visitante");
        lblEquipoVisitanteB3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB3.setText("NombreEstadio");

        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setText("-");

        javax.swing.GroupLayout panelBFila3Layout = new javax.swing.GroupLayout(panelBFila3);
        panelBFila3.setLayout(panelBFila3Layout);
        panelBFila3Layout.setHorizontalGroup(
            panelBFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB3)
                    .addGroup(panelBFila3Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila3Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB3)))
                .addContainerGap())
        );
        panelBFila3Layout.setVerticalGroup(
            panelBFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila3Layout.createSequentialGroup()
                .addGroup(panelBFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB3))
                    .addGroup(panelBFila3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB3)
                            .addComponent(lblEquipoLocalB3)
                            .addComponent(golesField1_B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 730, 90));

        lblFechaPartidoB4.setText("FechaPartido");

        lblEquipoLocalB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB4.setText("Equipo Local");

        lblEquipoVisitanteB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB4.setText("Equipo Visitante");
        lblEquipoVisitanteB4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB4.setText("NombreEstadio");

        guionB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionB4.setText("-");

        javax.swing.GroupLayout panelBFila4Layout = new javax.swing.GroupLayout(panelBFila4);
        panelBFila4.setLayout(panelBFila4Layout);
        panelBFila4Layout.setHorizontalGroup(
            panelBFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB4)
                    .addGroup(panelBFila4Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila4Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB4)))
                .addContainerGap())
        );
        panelBFila4Layout.setVerticalGroup(
            panelBFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila4Layout.createSequentialGroup()
                .addGroup(panelBFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB4))
                    .addGroup(panelBFila4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB4)
                            .addComponent(lblEquipoLocalB4)
                            .addComponent(golesField1_B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionB4))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 730, 90));

        lblFechaPartidoB5.setText("FechaPartido");

        lblEquipoLocalB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB5.setText("Equipo Local");

        lblEquipoVisitanteB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB5.setText("Equipo Visitante");
        lblEquipoVisitanteB5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB5.setText("NombreEstadio");

        guionB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionB5.setText("-");

        javax.swing.GroupLayout panelBFila5Layout = new javax.swing.GroupLayout(panelBFila5);
        panelBFila5.setLayout(panelBFila5Layout);
        panelBFila5Layout.setHorizontalGroup(
            panelBFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB5)
                    .addGroup(panelBFila5Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila5Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB5)))
                .addContainerGap())
        );
        panelBFila5Layout.setVerticalGroup(
            panelBFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila5Layout.createSequentialGroup()
                .addGroup(panelBFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB5))
                    .addGroup(panelBFila5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB5)
                            .addComponent(lblEquipoLocalB5)
                            .addComponent(golesField1_B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionB5))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 730, 90));

        lblFechaPartidoB6.setText("FechaPartido");

        lblEquipoLocalB6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoLocalB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoLocalB6.setText("Equipo Local");

        lblEquipoVisitanteB6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEquipoVisitanteB6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipoVisitanteB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/banderas/placeholder.png"))); // NOI18N
        lblEquipoVisitanteB6.setText("Equipo Visitante");
        lblEquipoVisitanteB6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNombreEstadioB6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreEstadioB6.setText("NombreEstadio");

        guionB6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionB6.setText("-");

        javax.swing.GroupLayout panelBFila6Layout = new javax.swing.GroupLayout(panelBFila6);
        panelBFila6.setLayout(panelBFila6Layout);
        panelBFila6Layout.setHorizontalGroup(
            panelBFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorB6)
                    .addGroup(panelBFila6Layout.createSequentialGroup()
                        .addComponent(lblFechaPartidoB6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreEstadioB6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBFila6Layout.createSequentialGroup()
                        .addComponent(lblEquipoLocalB6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(golesField1_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guionB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golesField2_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEquipoVisitanteB6)))
                .addContainerGap())
        );
        panelBFila6Layout.setVerticalGroup(
            panelBFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBFila6Layout.createSequentialGroup()
                .addGroup(panelBFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBFila6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFechaPartidoB6))
                    .addGroup(panelBFila6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreEstadioB6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBFila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipoVisitanteB6)
                            .addComponent(lblEquipoLocalB6)
                            .addComponent(golesField1_B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(golesField2_B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guionB6))))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInteriorB.add(panelBFila6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 730, 90));

        jScrollPaneB.setViewportView(panelInteriorB);

        panelGrupoB.add(jScrollPaneB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, 420));

        tabbedPane.addTab("B", panelGrupoB);

        javax.swing.GroupLayout panelGrupoCLayout = new javax.swing.GroupLayout(panelGrupoC);
        panelGrupoC.setLayout(panelGrupoCLayout);
        panelGrupoCLayout.setHorizontalGroup(
            panelGrupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoCLayout.setVerticalGroup(
            panelGrupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("C", panelGrupoC);

        javax.swing.GroupLayout panelGrupoDLayout = new javax.swing.GroupLayout(panelGrupoD);
        panelGrupoD.setLayout(panelGrupoDLayout);
        panelGrupoDLayout.setHorizontalGroup(
            panelGrupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoDLayout.setVerticalGroup(
            panelGrupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("D", panelGrupoD);

        javax.swing.GroupLayout panelGrupoELayout = new javax.swing.GroupLayout(panelGrupoE);
        panelGrupoE.setLayout(panelGrupoELayout);
        panelGrupoELayout.setHorizontalGroup(
            panelGrupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoELayout.setVerticalGroup(
            panelGrupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("E", panelGrupoE);

        javax.swing.GroupLayout panelGrupoFLayout = new javax.swing.GroupLayout(panelGrupoF);
        panelGrupoF.setLayout(panelGrupoFLayout);
        panelGrupoFLayout.setHorizontalGroup(
            panelGrupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoFLayout.setVerticalGroup(
            panelGrupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("F", panelGrupoF);

        javax.swing.GroupLayout panelGrupoGLayout = new javax.swing.GroupLayout(panelGrupoG);
        panelGrupoG.setLayout(panelGrupoGLayout);
        panelGrupoGLayout.setHorizontalGroup(
            panelGrupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoGLayout.setVerticalGroup(
            panelGrupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("G", panelGrupoG);

        javax.swing.GroupLayout panelGrupoHLayout = new javax.swing.GroupLayout(panelGrupoH);
        panelGrupoH.setLayout(panelGrupoHLayout);
        panelGrupoHLayout.setHorizontalGroup(
            panelGrupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelGrupoHLayout.setVerticalGroup(
            panelGrupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("H", panelGrupoH);

        javax.swing.GroupLayout panelOctavosLayout = new javax.swing.GroupLayout(panelOctavos);
        panelOctavos.setLayout(panelOctavosLayout);
        panelOctavosLayout.setHorizontalGroup(
            panelOctavosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelOctavosLayout.setVerticalGroup(
            panelOctavosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("OCTAVOS", panelOctavos);

        javax.swing.GroupLayout panelCuartosLayout = new javax.swing.GroupLayout(panelCuartos);
        panelCuartos.setLayout(panelCuartosLayout);
        panelCuartosLayout.setHorizontalGroup(
            panelCuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelCuartosLayout.setVerticalGroup(
            panelCuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("CUARTOS", panelCuartos);

        javax.swing.GroupLayout panelSemifinalesLayout = new javax.swing.GroupLayout(panelSemifinales);
        panelSemifinales.setLayout(panelSemifinalesLayout);
        panelSemifinalesLayout.setHorizontalGroup(
            panelSemifinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelSemifinalesLayout.setVerticalGroup(
            panelSemifinalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("SEMIFINALES", panelSemifinales);

        javax.swing.GroupLayout panelTercerPuestoLayout = new javax.swing.GroupLayout(panelTercerPuesto);
        panelTercerPuesto.setLayout(panelTercerPuestoLayout);
        panelTercerPuestoLayout.setHorizontalGroup(
            panelTercerPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelTercerPuestoLayout.setVerticalGroup(
            panelTercerPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("3er PUESTO", panelTercerPuesto);

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabbedPane.addTab("FINAL", panelFinal);

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 505, Short.MAX_VALUE))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabbedPane.getAccessibleContext().setAccessibleName("tabB");

        labelTitulo.setBackground(new java.awt.Color(46, 30, 34));
        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(154, 16, 50));
        labelTitulo.setText("QATAR 2022 - FIXTURE");

        labelSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSubtitulo.setForeground(new java.awt.Color(154, 16, 50));
        labelSubtitulo.setText("del 21 de noviembre al 18 de diciembre de 2022");

        labelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/img/qatar_2022_logo.png"))); // NOI18N
        labelLogo1.setText("LOGO");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(labelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(611, Short.MAX_VALUE)))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubtitulo)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelHeaderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private GrupoRepository grupoRepository;
    private PartidoRepository partidoRepository ;  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B3;
    private javax.swing.JFormattedTextField golesField1_A1;
    private javax.swing.JFormattedTextField golesField1_A2;
    private javax.swing.JFormattedTextField golesField1_A3;
    private javax.swing.JFormattedTextField golesField1_A4;
    private javax.swing.JFormattedTextField golesField1_A5;
    private javax.swing.JFormattedTextField golesField1_A6;
    private javax.swing.JFormattedTextField golesField1_B1;
    private javax.swing.JFormattedTextField golesField1_B2;
    private javax.swing.JFormattedTextField golesField1_B3;
    private javax.swing.JFormattedTextField golesField1_B4;
    private javax.swing.JFormattedTextField golesField1_B5;
    private javax.swing.JFormattedTextField golesField1_B6;
    private javax.swing.JFormattedTextField golesField2_A1;
    private javax.swing.JFormattedTextField golesField2_A2;
    private javax.swing.JFormattedTextField golesField2_A3;
    private javax.swing.JFormattedTextField golesField2_A4;
    private javax.swing.JFormattedTextField golesField2_A5;
    private javax.swing.JFormattedTextField golesField2_A6;
    private javax.swing.JFormattedTextField golesField2_B1;
    private javax.swing.JFormattedTextField golesField2_B2;
    private javax.swing.JFormattedTextField golesField2_B3;
    private javax.swing.JFormattedTextField golesField2_B4;
    private javax.swing.JFormattedTextField golesField2_B5;
    private javax.swing.JFormattedTextField golesField2_B6;
    private javax.swing.JLabel guionA1;
    private javax.swing.JLabel guionA2;
    private javax.swing.JLabel guionA3;
    private javax.swing.JLabel guionA4;
    private javax.swing.JLabel guionA5;
    private javax.swing.JLabel guionA6;
    private javax.swing.JLabel guionA7;
    private javax.swing.JLabel guionB2;
    private javax.swing.JLabel guionB4;
    private javax.swing.JLabel guionB5;
    private javax.swing.JLabel guionB6;
    private javax.swing.JScrollPane jScrollPaneA;
    private javax.swing.JScrollPane jScrollPaneB;
    private javax.swing.JSeparator jSeparatorA1;
    private javax.swing.JSeparator jSeparatorA2;
    private javax.swing.JSeparator jSeparatorA3;
    private javax.swing.JSeparator jSeparatorA4;
    private javax.swing.JSeparator jSeparatorA5;
    private javax.swing.JSeparator jSeparatorA6;
    private javax.swing.JSeparator jSeparatorB1;
    private javax.swing.JSeparator jSeparatorB2;
    private javax.swing.JSeparator jSeparatorB3;
    private javax.swing.JSeparator jSeparatorB4;
    private javax.swing.JSeparator jSeparatorB5;
    private javax.swing.JSeparator jSeparatorB6;
    private javax.swing.JLabel labelLogo1;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lblEquipoLocalA1;
    private javax.swing.JLabel lblEquipoLocalA2;
    private javax.swing.JLabel lblEquipoLocalA3;
    private javax.swing.JLabel lblEquipoLocalA4;
    private javax.swing.JLabel lblEquipoLocalA5;
    private javax.swing.JLabel lblEquipoLocalA6;
    private javax.swing.JLabel lblEquipoLocalB1;
    private javax.swing.JLabel lblEquipoLocalB2;
    private javax.swing.JLabel lblEquipoLocalB3;
    private javax.swing.JLabel lblEquipoLocalB4;
    private javax.swing.JLabel lblEquipoLocalB5;
    private javax.swing.JLabel lblEquipoLocalB6;
    private javax.swing.JLabel lblEquipoVisitanteA1;
    private javax.swing.JLabel lblEquipoVisitanteA2;
    private javax.swing.JLabel lblEquipoVisitanteA3;
    private javax.swing.JLabel lblEquipoVisitanteA4;
    private javax.swing.JLabel lblEquipoVisitanteA5;
    private javax.swing.JLabel lblEquipoVisitanteA6;
    private javax.swing.JLabel lblEquipoVisitanteB1;
    private javax.swing.JLabel lblEquipoVisitanteB2;
    private javax.swing.JLabel lblEquipoVisitanteB3;
    private javax.swing.JLabel lblEquipoVisitanteB4;
    private javax.swing.JLabel lblEquipoVisitanteB5;
    private javax.swing.JLabel lblEquipoVisitanteB6;
    private javax.swing.JLabel lblFechaPartidoA1;
    private javax.swing.JLabel lblFechaPartidoA2;
    private javax.swing.JLabel lblFechaPartidoA3;
    private javax.swing.JLabel lblFechaPartidoA4;
    private javax.swing.JLabel lblFechaPartidoA5;
    private javax.swing.JLabel lblFechaPartidoA6;
    private javax.swing.JLabel lblFechaPartidoB1;
    private javax.swing.JLabel lblFechaPartidoB2;
    private javax.swing.JLabel lblFechaPartidoB3;
    private javax.swing.JLabel lblFechaPartidoB4;
    private javax.swing.JLabel lblFechaPartidoB5;
    private javax.swing.JLabel lblFechaPartidoB6;
    private javax.swing.JLabel lblNombreEstadioA1;
    private javax.swing.JLabel lblNombreEstadioA2;
    private javax.swing.JLabel lblNombreEstadioA3;
    private javax.swing.JLabel lblNombreEstadioA4;
    private javax.swing.JLabel lblNombreEstadioA5;
    private javax.swing.JLabel lblNombreEstadioA6;
    private javax.swing.JLabel lblNombreEstadioB1;
    private javax.swing.JLabel lblNombreEstadioB2;
    private javax.swing.JLabel lblNombreEstadioB3;
    private javax.swing.JLabel lblNombreEstadioB4;
    private javax.swing.JLabel lblNombreEstadioB5;
    private javax.swing.JLabel lblNombreEstadioB6;
    private javax.swing.JPanel panelAFila1;
    private javax.swing.JPanel panelAFila2;
    private javax.swing.JPanel panelAFila3;
    private javax.swing.JPanel panelAFila4;
    private javax.swing.JPanel panelAFila5;
    private javax.swing.JPanel panelAFila6;
    private javax.swing.JPanel panelBFila1;
    private javax.swing.JPanel panelBFila2;
    private javax.swing.JPanel panelBFila3;
    private javax.swing.JPanel panelBFila4;
    private javax.swing.JPanel panelBFila5;
    private javax.swing.JPanel panelBFila6;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelCuartos;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelGrupoA;
    private javax.swing.JPanel panelGrupoB;
    private javax.swing.JPanel panelGrupoC;
    private javax.swing.JPanel panelGrupoD;
    private javax.swing.JPanel panelGrupoE;
    private javax.swing.JPanel panelGrupoF;
    private javax.swing.JPanel panelGrupoG;
    private javax.swing.JPanel panelGrupoH;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInteriorA;
    private javax.swing.JPanel panelInteriorB;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelOctavos;
    private javax.swing.JPanel panelSemifinales;
    private javax.swing.JPanel panelTercerPuesto;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private void loadPartidosGrupoA() {
    
       javax.swing.JLabel [] fechasA = {
           lblFechaPartidoA1,
           lblFechaPartidoA2,
           lblFechaPartidoA2,
           lblFechaPartidoA3,
           lblFechaPartidoA4,
           lblFechaPartidoA5
       };
       
       javax.swing.JLabel [] equipoLocales = {
           lblEquipoLocalA1,
           lblEquipoLocalA2,
           lblEquipoLocalA3,
           lblEquipoLocalA4,
           lblEquipoLocalA5,
           lblEquipoLocalA6
       };
       
       javax.swing.JLabel [] estadiosA = {
           lblNombreEstadioA1,
           lblNombreEstadioA2,
           lblNombreEstadioA3,
           lblNombreEstadioA4,
           lblNombreEstadioA5,
           lblNombreEstadioA6,
       };
       
       javax.swing.JLabel [] equiposVisitantes = {
           lblEquipoVisitanteA1,
           lblEquipoVisitanteA2,
           lblEquipoVisitanteA3,
           lblEquipoVisitanteA4,
           lblEquipoVisitanteA5,
           lblEquipoVisitanteA6,
       };
       
               
       Grupo grupoA = grupoRepository.get('a');
    
       ArrayList<Partido> partidos = partidoRepository.findBy(Fase.DE_GRUPOS, grupoA);
    
      Collections.sort(partidos, new Comparator<Partido>(){
           @Override
           public int compare(Partido p1, Partido p2) {
               return p1.getFechaYHora().isBefore(p2.getFechaYHora()) ? -1 : 1;
          }
      });
      
      List<Partido> partidosOrdenados =  partidos.stream()
        .sorted(Comparator.comparing(Partido::getFechaYHora))
        .collect(Collectors.toList());
      
       int i= 0;
       for(Partido p : partidos ){
           
          fechasA[i].setText(p.getFechaYHora().toString());

            equipoLocales[i].setText(p.getEquipo1().getNombre());

            // Bandera equipo local
            ImageIcon imagenEquipoLocal = new ImageIcon("src/static/img/banderas/" + p.getEquipo1().getId() + ".png");
            
            // Achico la imagen
            ImageIcon imagenEquipoLocalAchicada = new ImageIcon(imagenEquipoLocal.getImage().getScaledInstance(50, 33, Image.SCALE_SMOOTH));
            
            // Vinculo la imagen con el label
            equipoLocales[i].setIcon(imagenEquipoLocalAchicada);

            estadiosA[i].setText("Estado " + p.getEstadio().getNombre());

            equiposVisitantes[i].setText(p.getEquipo2().getNombre());
            
            // Bandera equipo visitante
            ImageIcon imagenEquipoVisitante = new ImageIcon("src/static/img/banderas/" + p.getEquipo2().getId() + ".png");
            
            // Achico la imagen
            ImageIcon imagenEquipoVisitanteAchicada = new ImageIcon(imagenEquipoVisitante.getImage().getScaledInstance(50, 33, Image.SCALE_SMOOTH));
            
            // Vinculo la imagen con el label
            equiposVisitantes[i].setIcon(imagenEquipoVisitanteAchicada);
            equiposVisitantes[i].setHorizontalTextPosition(JLabel.LEFT);
            
            i++;
       }
        
    }

    private void loadPartidosGrupoB() {


       
    }
 
    
    private void cargarRepositorios() {
    
       GruposMigrations.up();
       PartidosMigrations.up();
       
       grupoRepository = new GrupoRepository();
       partidoRepository = new PartidoRepository();
    }
}
